In [1]:
import descents as d
import linear_regression as lr

In [3]:
import pandas as pd
import seaborn as sns
import numpy as np

sns.set_theme()

# data = pd.DataFrame([{'iteration': i, 'lr': tdlr.get_lr(i)} for i in range(20)])

# sns.lmplot(data=data, x='iteration', y='lr')

In [67]:
ident = np.identity(10)

r_indices = np.random.choice(ident.shape[0], 3, replace=True)
ident[r_indices]

array([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]])

In [68]:
r_indices

array([8, 6, 6], dtype=int32)

In [69]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [79]:
np.empty([3, 4])[[2]]

array([[0., 0., 0., 1.]])

In [5]:
import numpy as np
a = np.ones([3, 4])
b = a.copy()

In [6]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
b[0][0] = 0
b[1][1] = 3

In [15]:
np.sqrt(b)

array([[0.        , 1.        , 1.        , 1.        ],
       [1.        , 1.73205081, 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        ]])

In [11]:
b.iloc[[0, 2]]

AttributeError: 'numpy.ndarray' object has no attribute 'iloc'

In [22]:
c = (np.random.randn(10) * 10).round(0)
c

array([ -0.,   5.,   8., -20., -19.,  10.,   1.,   7.,   6.,  -8.])

In [24]:
np.linalg.norm(c)

np.float64(33.166247903554)

In [26]:
s = 0 

for i in range(10):
    s += c[i] ** 2 

np.sqrt(s)

np.float64(33.166247903554)

In [45]:
import scipy as sp

c = (np.random.randn(15, 10) * 10).round(0)
c

array([[-11.,   9.,  -8.,  13., -25.,   3.,   1.,  11.,   1.,   0.],
       [ -6., -17.,  -3.,  -7.,   9., -10.,  -7.,  -9.,   3.,   1.],
       [  0.,   4.,  -4.,  -8.,  19.,  -8.,  -1.,  10.,   1.,   6.],
       [-11.,   6.,  -4.,  -2., -10.,  -1.,  -5.,  12.,  12.,   7.],
       [-11.,  -1.,   8.,  10., -20.,  22.,  18.,  -0.,  -3.,  -6.],
       [  9., -13.,   1.,  -5.,  11.,   2.,   7.,   1.,  -1.,   6.],
       [ -4.,   4.,   2.,   1.,   7., -10.,  -0.,  -9.,   8.,  31.],
       [ -6.,   6.,   5.,  -2.,  -5.,   1., -26.,  -9.,  14.,   3.],
       [ 16.,   1., -10.,  -0.,  -3.,   3., -15.,  27.,   3., -13.],
       [-12.,  -9.,  -7., -15.,   5.,   6.,  -6.,  10.,  -2.,  -5.],
       [-15., -21.,  15.,  -2., -17.,  -8.,  -9.,   6.,   1.,  13.],
       [  4.,  12.,   5.,   0.,  -6.,  12.,   4.,   4.,   2.,  -1.],
       [  4.,  17.,  14.,  -8.,  -2.,   2.,  -3.,  14.,  -2.,  -1.],
       [  4.,  11.,   9., -12.,   1.,   2.,   3.,   1.,   5.,  -6.],
       [ 19.,   3., -23.,   1.,  -

In [46]:
u_matrix, sigma_matrix, vt_matrix = sp.sparse.linalg.svds(c, 6)

In [47]:
u_matrix * sigma_matrix @ vt_matrix

array([[-8.32420865e+00,  6.92526210e+00, -5.88675600e+00,
         1.39946442e+01, -2.45816992e+01,  5.78202507e+00,
         9.16829704e-01,  1.26268591e+01,  1.81254375e+00,
         2.72407372e+00],
       [-4.02940507e+00, -1.81198290e+01, -6.01380178e-01,
        -6.66079452e+00,  9.02311145e+00, -8.15442488e+00,
        -7.68537817e+00, -7.34310072e+00, -4.98370224e-03,
         4.15055535e+00],
       [ 4.46564643e+00,  2.62779298e+00, -2.49790803e+00,
        -7.30979884e+00,  1.61243856e+01, -1.16508197e+01,
        -4.65869751e-01,  9.61200594e+00,  2.80317955e+00,
         5.05359956e+00],
       [-8.19217577e+00,  5.59214582e+00,  3.24731168e-01,
         1.46759672e+00, -1.07325802e+01, -4.20797016e+00,
        -7.16309989e+00,  1.31029454e+01,  6.88372423e+00,
         7.36661875e+00],
       [-9.67725634e+00,  1.79538006e-01,  8.71850104e+00,
         1.14160102e+01, -2.26241073e+01,  1.46800460e+01,
         1.73826422e+01, -1.64546532e+00, -4.59830843e+00,
        -9.

In [27]:
v_matrix.shape

(4, 10)

In [25]:
u_matrix.shape

(15, 4)

In [28]:
sigma_matrix.shape

(4,)

In [35]:
u_matrix * sigma_matrix @ v_matrix

array([[  4.46270418,   4.19838835,   2.80634768,  -8.22174966,
         -3.23257616,   4.74532831,  -6.35424701,  -4.07868214,
         -5.03005531,  -1.67994526],
       [  2.2903607 ,  -1.60888774,  -8.54497548,   2.68494611,
         -3.66905296,   9.4310892 ,   0.17948261,  22.10804164,
         25.92416128, -14.34069508],
       [ -1.15416676,   1.93263759,  -9.02826232,   1.2895828 ,
          7.14998827,  -9.0965032 ,   5.84782922,   7.7805818 ,
          8.4466742 ,  13.99729862],
       [  0.72231605,  -9.12625456,  -1.99900435,  12.44236749,
          2.75535402,  -4.59548325,   3.14455038,  11.27886209,
         14.90117002,   3.20437087],
       [  9.30994543,   3.38926313,   1.86401125,  -8.62080047,
         -2.8380857 ,   4.23271084,  -9.37709002,   1.09440814,
          1.64353908,   2.59232805],
       [  1.89087468,  -5.41824465,   8.83574734,   3.8710772 ,
         -1.87474266,  -0.28791051,  -3.72771787,  -7.93894973,
         -7.7905156 ,  -0.27785086],
       [ 2

In [52]:
(vt_matrix.T / sigma_matrix) @ (u_matrix.T) 

array([[-2.66031605e-03, -2.15964493e-03,  1.41664386e-03,
        -3.18730724e-03, -2.63715700e-03,  9.17820801e-04,
        -1.04834773e-03, -2.01634341e-03,  2.10447720e-03,
        -2.21334517e-03, -8.94912672e-03,  1.31842368e-03,
         4.74808442e-04,  1.05036496e-03,  5.44337986e-03],
       [ 2.31482280e-03, -8.60561339e-03,  2.56012600e-03,
         3.08386135e-03, -1.76316948e-03, -4.02322658e-03,
         6.88762498e-03,  3.66261299e-03, -5.72072425e-04,
        -7.50285050e-03, -9.01049448e-03,  6.54406772e-03,
         8.81877229e-03,  5.78535474e-03,  4.69582529e-04],
       [-8.09752599e-03,  9.38054986e-04, -3.09742754e-03,
        -2.10217749e-03,  3.63799564e-03, -1.66748566e-03,
        -3.19038694e-03,  9.35626313e-03, -6.89338393e-03,
         1.41441331e-03,  4.38575141e-03,  3.91449357e-03,
         8.66311893e-03,  1.01964148e-02, -7.68509438e-03],
       [ 8.59953552e-03, -3.38060772e-03, -1.00678019e-03,
         1.61752208e-03,  2.78626033e-03, -5.76329372

In [68]:
a = np.array(range(60)).reshape([12, 5]).astype(float)

In [69]:
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34.],
       [35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44.],
       [45., 46., 47., 48., 49.],
       [50., 51., 52., 53., 54.],
       [55., 56., 57., 58., 59.]])

In [55]:
s = np.array(range(5))

In [56]:
s

array([0, 1, 2, 3, 4])

In [58]:
s * a

array([[  0,   1,   4,   9,  16],
       [  0,   6,  14,  24,  36],
       [  0,  11,  24,  39,  56],
       [  0,  16,  34,  54,  76],
       [  0,  21,  44,  69,  96],
       [  0,  26,  54,  84, 116],
       [  0,  31,  64,  99, 136],
       [  0,  36,  74, 114, 156],
       [  0,  41,  84, 129, 176],
       [  0,  46,  94, 144, 196],
       [  0,  51, 104, 159, 216],
       [  0,  56, 114, 174, 236]])

In [70]:
a[3][3] = np.sqrt(-1)

C:\Users\Пользователь\AppData\Local\Temp\ipykernel_18812\3843332291.py:1: RuntimeWarning: invalid value encountered in sqrt
  a[3][3] = np.sqrt(-1)


In [79]:
s.T

array([0, 1, 2, 3, 4])