In [1]:
import descents as d
import linear_regression as lr

In [6]:
import pandas as pd
import seaborn as sns
import numpy as np

sns.set_theme()

data = pd.DataFrame([{'iteration': i, 'lr': tdlr.get_lr(i)} for i in range(20)])

sns.lmplot(data=data, x='iteration', y='lr')

NameError: name 'tdlr' is not defined

In [67]:
ident = np.identity(10)

r_indices = np.random.choice(ident.shape[0], 3, replace=True)
ident[r_indices]

array([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]])

In [68]:
r_indices

array([8, 6, 6], dtype=int32)

In [69]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [79]:
np.empty([3, 4])[[2]]

array([[0., 0., 0., 1.]])

In [5]:
import numpy as np
a = np.ones([3, 4])
b = a.copy()

In [6]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
b[0][0] = 0
b[1][1] = 3

In [15]:
np.sqrt(b)

array([[0.        , 1.        , 1.        , 1.        ],
       [1.        , 1.73205081, 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        ]])

In [11]:
b.iloc[[0, 2]]

AttributeError: 'numpy.ndarray' object has no attribute 'iloc'

In [22]:
c = (np.random.randn(10) * 10).round(0)
c

array([ -0.,   5.,   8., -20., -19.,  10.,   1.,   7.,   6.,  -8.])

In [24]:
np.linalg.norm(c)

np.float64(33.166247903554)

In [26]:
s = 0 

for i in range(10):
    s += c[i] ** 2 

np.sqrt(s)

np.float64(33.166247903554)